baseURL = 'https://coruscating-conkies-9af9d6.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
date_format = 'January 2, 2006'

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.main]]
  name = "About"
  url = "/accessibility/"
  weight = 2
  [[menu.main]]
  name = "Blog"
  url = "/posts/"

