baseURL = 'https://coruscating-conkies-9af9d6.netlify.app/'
languageCode = 'en-us'
title = 'Learn about Web Accessibility'
theme = 'ananke'
date_format = 'January 2, 2006'




[menu]
  [[menu.main]]
  name = "Home"
  url = "/posts/"
  weight = 1
  [[menu.main]]
  name = "Accessibilty Features"
  url = "/accessibility/"
  weight = 2
 

 [[menu.main]]
  name = "Feedback"
  url = "/feedback/"
  weight = 4

[taxonomies]
    feedback_tag = "feedback_tags"
 tag = 'tags'